installing additional package
needed: 
```
ERROR: (gcloud.components.update) 
You cannot perform this action because the Cloud SDK component manager 
is disabled for this installation. You can run the following command 
to achieve the same result for this installation: 

sudo apt-get update && sudo apt-get --only-upgrade install google-cloud-sdk-firestore-emulator google-cloud-sdk-app-engine-go google-cloud-sdk-datalab google-cloud-sdk-anthos-auth google-cloud-sdk-pubsub-emulator google-cloud-sdk-kind google-cloud-sdk-app-engine-python-extras google-cloud-sdk-app-engine-java google-cloud-sdk-datastore-emulator google-cloud-sdk-skaffold google-cloud-sdk-app-engine-python google-cloud-sdk-bigtable-emulator google-cloud-sdk google-cloud-sdk-cloud-build-local google-cloud-sdk-minikube kubectl google-cloud-sdk-cbt google-cloud-sdk-app-engine-grpc google-cloud-sdk-spanner-emulator google-cloud-sdk-kpt

```